site_name: ZCY's blog
site_description: 记录学习过程中的笔记和思考
site_author: 某晨某
site_url: https://mouchenmou.github.io/ZCY-s-website/

# Repository
repo_name: zcy's website
repo_url: https://github.com/mouchenmou/ZCY-s-website
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2025 某晨某

theme:
  name: material
  language: zh
  logo: assets/IMG/1.jpg
  favicon: assets/IMG/1.jpg
  palette:
    # Palette toggle for light mode - 自定义米黄绿色主题
    - scheme: warm
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mouchenmou
      name: GitHub

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - 首页: index.md
  - Undergraduate Study:
    - undergraduate-study/index1.md
    - CS61B 数据结构:
      - 笔记本/CS61B/index.md
      - Lecture 1 - Java基础: 笔记本/CS61B/Lecture 1/Intro 1 Study Guide.md
      - Lecture 2 - Java语法: 笔记本/CS61B/Lecture 2/一些关于java的语法.md
      - Lecture 13 - 渐近线1: 笔记本/CS61B/Lecture 13 渐近线1/Big O.md
      - Lecture 14 - 不相交集1:
        - 笔记本/CS61B/Lecture 14 不相交集1(Disjoint Sets)/1.快速查找不相交集（QuickFindDS）.md
        - 笔记本/CS61B/Lecture 14 不相交集1(Disjoint Sets)/2.快速连接法（QuickUnionDS）.md
        - 笔记本/CS61B/Lecture 14 不相交集1(Disjoint Sets)/3.加权快速接头（Weighted Quick Union）.md
      - Lecture 15 - 不相交集2和渐近线2:
        - 笔记本/CS61B/Lecture 15 不相交集2和渐近线2/15.1 路径压缩(WQU with Path Compression).md
        - 笔记本/CS61B/Lecture 15 不相交集2和渐近线2/15.2 渐近线2.md
      - Lecture 16 - 二分查找法和BSTs:
        - 16.1 二分查找法: 笔记本/CS61B/Lecture 16 二分查找法，ADTs，BSTs/二分查找法（BinarySearch）.md
        - 16.2 归并排序: 笔记本/CS61B/Lecture 16 二分查找法，ADTs，BSTs/归并排序（Mergesort）.md
        - 16.3 BSTs: 笔记本/CS61B/Lecture 16 二分查找法，ADTs，BSTs/BSTs.md
      - Lecture 17 - 二叉搜索树:
        - 17.1 BST的insert: 笔记本/CS61B/Lecture 17 二叉搜索树，Set and Maps，B-trees/1.BST的insert.md
        - 17.2 BST的delete: 笔记本/CS61B/Lecture 17 二叉搜索树，Set and Maps，B-trees/2.BST删除节点.md
        - 17.3 集合与映射: 笔记本/CS61B/Lecture 17 二叉搜索树，Set and Maps，B-trees/3.集合与映射（Set and Maps）.md
        - 17.4 二叉搜索树的高度和最坏情况: 笔记本/CS61B/Lecture 17 二叉搜索树，Set and Maps，B-trees/4.二叉搜索树的高度和最坏情况.md
        - 17.5 B-Trees: 笔记本/CS61B/Lecture 17 二叉搜索树，Set and Maps，B-trees/5.B-Trees.md
      - Lecture 18 - 旋转树和红黑树:
        - 18.1 Definition of Tree Rotation: 笔记本/CS61B/Lecture 18 旋转树和红黑树/1.Definition of Tree Rotation.md
        - 18.2 红黑树: 笔记本/CS61B/Lecture 18 旋转树和红黑树/2.红黑树.md
      - Lecture 19 - 哈希算法1:
        - 19.1 BobaCounterSet: 笔记本/CS61B/Lecture 19 哈希算法1/19.1 BobaCounterSet.md
        - 19.2 Dynamic Array of list: 笔记本/CS61B/Lecture 19 哈希算法1/19.2 Dynamic Array Of Lists Set.md
      - Lecture 20 - 哈希算法2: 笔记本/CS61B/Lecture 20 哈希算法2/20 关于哈希算法的深层解析.md
      - Lecture 21 Priority Queues and Heaps:
        - 21.1 优先队列: 笔记本/CS61B/Lecture 21 Priority Queues and Heaps/21.1 优先队列.md
        - 21.2 堆: 笔记本/CS61B/Lecture 21 Priority Queues and Heaps/21.2 堆.md
    - undergraduate-study/index2.md
    - 面向对象程序设计:
      - Lecture 1: 笔记本/面向对象程序设计/Lecture 1/The first C++ program.md
      - Lecture 2: 
        - 1.类: 笔记本/面向对象程序设计/Lecture 2/1.类.md
        - 2.File I and O: 笔记本/面向对象程序设计/Lecture 2/2.File I and O.md
        - 3.Memory Model: 笔记本/面向对象程序设计/Lecture 2/3.Memory Model.md
        - 4.Pointers to Objects: 笔记本/面向对象程序设计/Lecture 2/4.Pointers to Objects.md
      - Lecture 3:
        - 1.衔接 Lecture 2 的指针内容: 笔记本/面向对象程序设计/Lecture 3/1.衔接 lecture 2 的指针内容.md
        - 2.Reference(引用): 笔记本/面向对象程序设计/Lecture 3/2.Reference(引用).md
        - 3.constants: 笔记本/面向对象程序设计/Lecture 3/3.constants.md
        - 4.Conversions: 笔记本/面向对象程序设计/Lecture 3/4.Conversions.md
        - 5.Passing address: 笔记本/面向对象程序设计/Lecture 3/5.Passing address.md
        - 6.Class: 笔记本/面向对象程序设计/Lecture 3/6.Class.md
      - Homework:
        - Homework 1: 笔记本/面向对象程序设计/Homework/Homework1/Homework.md
    - 大学物理实验:
      - 1.绪论:
        - 1.实验测量与误差分布: 笔记本/大学物理实验/1.绪论/1.实验测量与误差分布.md
        - 2.误差与不确定度: 笔记本/大学物理实验/1.绪论/2.误差与不确定度.md
        - 3.有效数字与实验数据处理: 笔记本/大学物理实验/1.绪论/3.有效数字与实验数据处理.md
    - 大学物理乙2: 
      - 第十二章 静电场: 
        - 12.4 高斯定理: 笔记本/大学物理乙2/第十二章 静电场/12.4 高斯定理.md
        - 12.5 利用高斯定理计算电场: 笔记本/大学物理乙2/第十二章 静电场/12.5 利用高斯定理计算电场.md
        - 12.6 电势: 笔记本/大学物理乙2/第十二章 静电场/12.6 电势.md
        - 12.7 电势梯度: 笔记本/大学物理乙2/第十二章 静电场/12.7 电势梯度.md
      - 第十三章 静电场中的导体和电介质: 
        - 13.1 导体的静电平衡: 笔记本/大学物理乙2/第十三章 静电场中的导体和电介质/13.1 导体的静电平衡.md
        - 13.2 外电场中的导体: 笔记本/大学物理乙2/第十三章 静电场中的导体和电介质/13.2 外电场中的导体.md
        - 13.3 电容 电容器: 笔记本/大学物理乙2/第十三章 静电场中的导体和电介质/13.3 电容 电容器.md
        - 13.4 静电场中的电介质: 笔记本/大学物理乙2/第十三章 静电场中的导体和电介质/13.4 静电场中的电介质.md
        - 13.5 电介质中的静电场的基本定理: 笔记本/大学物理乙2/第十三章 静电场中的导体和电介质/13.5 电介质中的静电场的基本定理.md
    - 电子电路基础:
      - 第1章 电路基本概述:
        - 1.2电路基础知识: 笔记本/电子电路基础/第1章 电路基本概述/1.2电路基础知识.md
        - 1.3基本电路元件: 笔记本/电子电路基础/第1章 电路基本概述/1.3基本电路元件.md
      - 第2章 电路的等效变换:
        - 2.1电路等效: 笔记本/电子电路基础/第2章 电路的等效变换/2.1 电路等效.md
        - 2.2基尔霍夫电压定律: 笔记本/电子电路基础/第2章 电路的等效变换/2.2 基尔霍夫电压定律.md
        - 2.3电阻电路的等效变换: 笔记本/电子电路基础/第2章 电路的等效变换/2.3 电阻电路的等效变换.md
        - 2.4储能元件电路的等效变换: 笔记本/电子电路基础/第2章 电路的等效变换/2.4 储能元件电路的等效变换.md
        - 2.5电源电路的等效变换: 笔记本/电子电路基础/第2章 电路的等效变换/2.5 电源电路的等效变换.md
      - 第3章 电路分析的基本方法和定理: 
        - 3.1电路分析的基本方法和定理: 笔记本/电子电路基础/第3章 电路分析的基本方法和定理/3.1 电路分析基础.md
        - 3.2网孔电流法: 笔记本/电子电路基础/第3章 电路分析的基本方法和定理/3.2 网孔电流法.md
        - 3.3节点电压法: 笔记本/电子电路基础/第3章 电路分析的基本方法和定理/3.3 节点电压法.md
        - 3.5电路定理: 笔记本/电子电路基础/第3章 电路分析的基本方法和定理/3.5 电路定理.md
      - 第4章 动态电路的时域分析:
        - 4.1一阶电路的响应: 笔记本/电子电路基础/第4章 动态电路的时域分析/4.1 一阶电路的响应.md
        - 4.2二阶电路的响应: 笔记本/电子电路基础/第4章 动态电路的时域分析/4.2 二阶电路的响应.md
        - 4.3一阶电路和二阶电路的越阶响应: 笔记本/电子电路基础/第4章 动态电路的时域分析/4.3 一阶电路和二阶电路的越阶响应.md
        - 4.4一阶电路和二阶电路的冲激响应: 笔记本/电子电路基础/第4章 动态电路的时域分析/4.4 一阶电路和二阶电路的冲击响应.md
      - 第5章 正弦交流电路: 
        - 5.1正弦量的基本概念: 笔记本/电子电路基础/第5章 正弦交流电路/5.1 正弦量的基本概念.md
        - 5.2正弦稳态电路的相量分析方法: 笔记本/电子电路基础/第5章 正弦交流电路/5.2 正弦稳态电路的相量分析方法.md
    - 工程力学:
      - 第2章:
        - 2.2约束的分类及约束力的特征: 笔记本/工程力学/第二章/2.2 约束的分类及约束力的特征.md 
  - Laboratory Work:
    - 实验记录: laboratory-work/experiments.md
    - 研究笔记: laboratory-work/research-notes.md

# Custom CSS
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
